Repository OpenCombine/OpenCombine, pull requests merged in 2019-12, with the labels that each got.

#114 Implement Delay
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.Delay.swift
  Tests/OpenCombineTests/Helpers/CustomPublisher.swift
  Tests/OpenCombineTests/Helpers/PriorityQueue.swift
  Tests/OpenCombineTests/Helpers/TestReflection.swift
  Tests/OpenCombineTests/Helpers/VirtualTimeScheduler.swift
  Tests/OpenCombineTests/PublisherTests/DeferredTests.swift
  Tests/OpenCombineTests/PublisherTests/DelayTests.swift
  Tests/OpenCombineTests/VirtualTimeSchedulerTests.swift
Labels: missing functionality

#116 Implement SubscribeOn
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.SubscribeOn.swift
  Tests/OpenCombineTests/Helpers/CustomPublisher.swift
  Tests/OpenCombineTests/Helpers/FairPriorityQueue.swift
  Tests/OpenCombineTests/Helpers/VirtualTimeScheduler.swift
  Tests/OpenCombineTests/PublisherTests/DelayTests.swift
  Tests/OpenCombineTests/PublisherTests/FlatMapTests.swift
  Tests/OpenCombineTests/PublisherTests/ReceiveOnTests.swift
  Tests/OpenCombineTests/PublisherTests/SubscribeOnTests.swift
Labels: missing functionality

#117 Implement MeasureInterval
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.MeasureInterval.swift
  Sources/OpenCombine/Publishers/Publishers.SubscribeOn.swift
  Tests/OpenCombineTests/Helpers/VirtualTimeScheduler.swift
  Tests/OpenCombineTests/PublisherTests/DelayTests.swift
  Tests/OpenCombineTests/PublisherTests/MeasureIntervalTests.swift
  Tests/OpenCombineTests/PublisherTests/ReceiveOnTests.swift
  Tests/OpenCombineTests/PublisherTests/SubscribeOnTests.swift
  Tests/OpenCombineTests/VirtualTimeSchedulerTests.swift
Labels: missing functionality

#90 Implement Publishers.Concatenate
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Just.swift
  Sources/OpenCombine/Publishers/Publishers.Concatenate.swift
  Tests/OpenCombineTests/Helpers/CommonTests.swift
  Tests/OpenCombineTests/Helpers/TestLifecycle.swift
  Tests/OpenCombineTests/Helpers/XCTUnwrap.swift
  Tests/OpenCombineTests/PublisherTests/ConcatenateTests.swift
  Tests/OpenCombineTests/PublisherTests/JustTests.swift
Labels: missing functionality

#122 Implement Publishers.ReplaceEmpty
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.ReplaceEmpty.swift
  Tests/OpenCombineTests/PublisherTests/ReplaceEmptyTests.swift
Labels: missing functionality

#126 Fix integer overflows in DispatchQueue.SchedulerTimeType.Stride
  Sources/OpenCombineDispatch/DispatchQueue+Scheduler.swift
  Tests/OpenCombineTests/DispatchTests/DispatchQueueSchedulerTests.swift
Labels: bug

#127 Implement URLSession.DataTaskPublisher
  RemainingFoundationInterface.swift
  Sources/OpenCombineFoundation/Helpers/Violations.swift
  Sources/OpenCombineFoundation/URLSession.swift
  Tests/OpenCombineTests/FoundationTests/URLSessionTests.swift
  Tests/OpenCombineTests/Helpers/TestReflection.swift
  Tests/OpenCombineTests/Helpers/TestingError.swift
  Tests/OpenCombineTests/Helpers/TrackingSubscriber.swift
  Tests/OpenCombineTests/PublisherTests/MapErrorTests.swift
Labels: missing functionality

#129 Work around the 'default will never be executed' warning on Linux
  .circleci/config.yml
  Sources/OpenCombineDispatch/DispatchQueue+Scheduler.swift
Labels: gardening

#130 Fix more overflows in DispatchQueue.SchedulerTimeType
  Sources/OpenCombineDispatch/DispatchQueue+Scheduler.swift
  Tests/OpenCombineTests/DispatchTests/DispatchQueueSchedulerTests.swift
Labels: bug

#136 Implement Publishers.DropUntilOutput
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.DropUntilOutput.swift
  Sources/OpenCombine/Publishers/Publishers.ReplaceEmpty.swift
  Tests/OpenCombineTests/PublisherTests/DropUntilOutputTests.swift
Labels: missing functionality

#137 Implement Publishers.CollectByCount
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.CollectByCount.swift
  Tests/OpenCombineTests/PublisherTests/CollectByCountTests.swift
Labels: missing functionality

#138 Implement Publishers.AssertNoFailure
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.AssertNoFailure.swift
  Tests/OpenCombineTests/PublisherTests/AssertNoFailureTests.swift
Labels: missing functionality
