Repository OpenCombine/OpenCombine, pull requests merged in 2019-10, with the labels that each got.

#73 Fix Sequence cancelation
  Sources/OpenCombine/Publishers/Publishers.Sequence.swift
  Tests/OpenCombineTests/PublisherTests/SequenceTests.swift
Labels: bug

#74 Fix the semantics to be compatible with Xcode 11.1
  Sources/OpenCombine/Subscribers/Subscribers.Assign.swift
  Sources/OpenCombine/Subscribers/Subscribers.Sink.swift
  Tests/OpenCombineTests/SubscribersTests/AssignTests.swift
  Tests/OpenCombineTests/SubscribersTests/SinkTests.swift
Labels: bug

#77 Update docs to match Xcode 11.1
  RemainingCombineInterface.swift
  Sources/OpenCombine/AnyCancellable.swift
  Sources/OpenCombine/AnyPublisher.swift
  Sources/OpenCombine/Published.swift
  Sources/OpenCombine/Publishers/Publishers.Multicast.swift
  Tests/OpenCombineTests/PublisherTests/MulticastTests.swift
Labels: documentation

#78 Bump Swift version on Travis for Linux
  .travis.yml
Labels: continuous integration

#79 Reenable compatibility tests
  .travis.yml
Labels: continuous integration

#88 Audit IgnoreOutput for thread safety, add more tests, make them pass
  Sources/OpenCombine/Publishers/Publishers.IgnoreOutput.swift
  Tests/OpenCombineTests/PublisherTests/IgnoreOutputTests.swift
Labels: bug, enhancement

#92 Publishers.Print: cancel new subscription if Inner is already subscribed
  Sources/OpenCombine/Publishers/Publishers.Print.swift
  Tests/OpenCombineTests/PublisherTests/PrintTests.swift
Labels: bug

#87 Audit DropWhile/TryDropWhile for thread safety
  Sources/OpenCombine/Publishers/Publishers.CompactMap.swift
  Sources/OpenCombine/Publishers/Publishers.DropWhile.swift
  Sources/OpenCombine/Publishers/Publishers.Filter.swift
  Tests/OpenCombineTests/Helpers/CommonTests.swift
  Tests/OpenCombineTests/PublisherTests/AllSatisfyTests.swift
  Tests/OpenCombineTests/PublisherTests/AutoconnectTests.swift
  Tests/OpenCombineTests/PublisherTests/CollectTests.swift
  Tests/OpenCombineTests/PublisherTests/CompactMapTests.swift
  Tests/OpenCombineTests/PublisherTests/ComparisonTests.swift
  Tests/OpenCombineTests/PublisherTests/ContainsTests.swift
  Tests/OpenCombineTests/PublisherTests/CountTests.swift
  Tests/OpenCombineTests/PublisherTests/DropTests.swift
  Tests/OpenCombineTests/PublisherTests/DropWhileTests.swift
  Tests/OpenCombineTests/PublisherTests/EncodeTests.swift
  Tests/OpenCombineTests/PublisherTests/FilterTests.swift
  Tests/OpenCombineTests/PublisherTests/FirstTests.swift
  Tests/OpenCombineTests/PublisherTests/FlatMapTests.swift
  Tests/OpenCombineTests/PublisherTests/IgnoreOutputTests.swift
  Tests/OpenCombineTests/PublisherTests/LastTests.swift
  Tests/OpenCombineTests/PublisherTests/MakeConnectableTests.swift
  Tests/OpenCombineTests/PublisherTests/MapErrorTests.swift
  Tests/OpenCombineTests/PublisherTests/MapKeyPathTests.swift
  Tests/OpenCombineTests/PublisherTests/MapTests.swift
  Tests/OpenCombineTests/PublisherTests/MulticastTests.swift
  Tests/OpenCombineTests/PublisherTests/PrintTests.swift
  Tests/OpenCombineTests/PublisherTests/ReduceTests.swift
  Tests/OpenCombineTests/PublisherTests/ReplaceErrorTests.swift
  Tests/OpenCombineTests/PublisherTests/ReplaceNilTests.swift
  Tests/OpenCombineTests/PublisherTests/ScanTests.swift
  Tests/OpenCombineTests/PublisherTests/SetFailureTypeTests.swift
Labels: bug, enhancement
