Repository OpenCombine/OpenCombine, pull requests merged in 2019-11, with the labels that each got.

#91 Implement Publishers.Output
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Optional.Publisher.swift
  Sources/OpenCombine/Publishers/Publishers.Output.swift
  Tests/OpenCombineTests/Helpers/CustomPublisher.swift
  Tests/OpenCombineTests/PublisherTests/JustTests.swift
  Tests/OpenCombineTests/PublisherTests/OptionalPublisherTests.swift
  Tests/OpenCombineTests/PublisherTests/OutputTests.swift
Labels: missing functionality

#100 Implement the Record publisher
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.Sequence.swift
  Sources/OpenCombine/Publishers/Record.swift
  Tests/OpenCombineTests/Helpers/TestReflection.swift
  Tests/OpenCombineTests/Helpers/TrackingEncoder.swift
  Tests/OpenCombineTests/PublisherTests/RecordTests.swift
Labels: missing functionality

#104 Warn about unguarded availability in C++ code. Fix the warnings.
  Makefile
  Sources/COpenCombineHelpers/COpenCombineHelpers.cpp
Labels: gardening

#110 If Multicast receives subscription twice, cancel the second one
  Sources/OpenCombine/Publishers/Publishers.Multicast.swift
  Tests/OpenCombineTests/Helpers/TrackingSubscriber.swift
  Tests/OpenCombineTests/PublisherTests/MulticastTests.swift
Labels: bug

#107 Add Future publisher with tests
  RemainingCombineInterface.swift
  Sources/OpenCombine/Future.swift
  Tests/OpenCombineTests/PublisherTests/FutureTests.swift
Labels: missing functionality

#112 Fix @Published
  .circleci/config.yml
  RemainingCombineInterface.swift
  Sources/OpenCombine/ObservableObject.swift
  Sources/OpenCombine/Published.swift
  Tests/OpenCombineTests/Helpers/TrackingSubscriber.swift
  Tests/OpenCombineTests/ObservableObjectPublisherTests.swift
  Tests/OpenCombineTests/PublishedTests.swift
Labels: bug
