Repository OpenCombine/OpenCombine, pull requests merged in 2019-09, with the labels that each got.

#50 ReplaceError implementation
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.ReplaceError.swift
  Tests/OpenCombineTests/PublisherTests/ReplaceErrorTests.swift
  Tests/OpenCombineTests/XCTestManifests.swift
Labels: missing functionality

#52 @propertyWrapper Published
  RemainingCombineInterface.swift
  Sources/OpenCombine/Published.swift
Labels: missing functionality

#45 FlatMap
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.FlatMap.swift
  Tests/OpenCombineTests/PublisherTests/FlatMapTests.swift
Labels: missing functionality

#59 Add eraseToAnyPublisher() method
  Sources/OpenCombine/AnyPublisher.swift
  Tests/OpenCombineTests/AnyPublisherTests.swift
Labels: missing functionality

#62 Fix iterator.next() being called twice in Publishers.Sequence
  Sources/OpenCombine/Publishers/Publishers.Sequence.swift
  Tests/OpenCombineTests/PublisherTests/SequenceTests.swift
Labels: bug

#61 Implement Publishers.MakeConnectable
  RemainingCombineInterface.swift
  Sources/OpenCombine/Publishers/Publishers.MakeConnectable.swift
  Tests/OpenCombineTests/PublisherTests/MakeConnectableTests.swift
  Tests/OpenCombineTests/PublisherTests/MulticastTests.swift
Labels: missing functionality

#63 Audit Publishers.Multicast for thread safety
  Sources/OpenCombine/Publishers/Publishers.Multicast.swift
  Tests/OpenCombineTests/PublisherTests/MakeConnectableTests.swift
  Tests/OpenCombineTests/PublisherTests/MulticastTests.swift
Labels: bug, enhancement

#64 Audit TryMap for thread safety, fix its semantics
  Sources/OpenCombine/Publishers/Publishers.Map.swift
  Tests/OpenCombineTests/Helpers/TestReflection.swift
  Tests/OpenCombineTests/PublisherTests/MapTests.swift
Labels: bug, enhancement
