Repository OpenCombine/OpenCombine, pull requests merged in 2021-01, with the labels that each got.

#201 Implementation for ObservableObject with Mirror
  Sources/OpenCombine/ObservableObject.swift
  Sources/OpenCombine/Published.swift
  Tests/OpenCombineTests/ObservableObjectTests.swift
Labels: missing functionality

#197 Add OpenCombineShim product for easier importing
  Package.swift
  Package@swift-5.0.swift
  Package@swift-5.1.swift
  Package@swift-5.2.swift
  Sources/OpenCombineShim/OpenCombineShim.swift
Labels: enhancement

#202 Add CHANGELOG.md, bump version to 0.12.0
  CHANGELOG.md
  OpenCombine.podspec
  OpenCombineDispatch.podspec
  OpenCombineFoundation.podspec
  README.md
Labels: documentation
